FROM node:22

RUN corepack enable && corepack prepare pnpm@10.29.3 --activate

WORKDIR /usr/src/app

COPY ./package.json ./pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 5173

CMD [ "pnpm", "vite", "--host", "0.0.0.0" ]
