# -----
# Stage 1 — Build : compile TS + bundle Vite → fichiers statiques

# On récupère une image capable de builder 
FROM node:22 AS builder

RUN corepack enable && corepack prepare pnpm@10.29.3 --activate

# On définit le répertoire de travail où exécuter les commandes
WORKDIR /usr/src/app

# On copie les packages et on lance l'installation des dépendances 
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# On copie le reste des fichiers séparément, puis on build
# La copie générale se fait après à cause du cache Docker : si les fichiers change, Docker ne relance pas l'installation des packages ainsi
COPY . .
RUN pnpm run build

# -----
# Stage 2 — Runner : Nginx sert les fichiers statiques

# On choisi une image légère
FROM nginx:alpine

# On copie les fichiers buildés
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# On expose le port
EXPOSE 80
