# On part d'une image existante
FROM node:22

# Repertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copie de package.json et package-lock.json dans le conteneur
COPY ./package.json ./pnpm-lock.yaml ./

# On lance NPM pour l'installation des dépendances
RUN npm install

# Copie du code dans le conteneur
COPY . .

# # On expose le port 5173 (port par défaut de Vite)
EXPOSE 5173

CMD [ "npx", "vite", "--host", "0.0.0.0" ]