# -----
# Stage 1 — Build : compile TypeScript → JavaScript

# On récupère une image capable de builder 
FROM node:22 AS builder

RUN corepack enable && corepack prepare pnpm@10.29.3 --activate

# On définit le répertoire de travail où exécuter les commandes
WORKDIR /usr/src/app

# On copie les packages et on lance l'installation des dépendances 
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# On copie le reste des fichiers séparément
# La copie générale se fait après à cause du cache Docker : si les fichiers change, Docker ne relance pas l'installation des packages ainsi
COPY . .
# On build l'appli et on supprime les fichiers de prod
RUN pnpm run build
RUN pnpm prune --prod

# -----
# Stage 2 — Runner : image légère, uniquement le JS compilé + deps de prod

# On choisi une image légère, le minimum pour faire tourner l'appli
FROM node:22-slim

# On définit le répertoire de travail où exécuter les commandes
WORKDIR /usr/src/app

# On copie les fichiers buildés
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./

# On expose le port
EXPOSE 3000

# On lance l'application
CMD ["node", "dist/index.js"]
