# On choisi une image pour faire tourner le backend
FROM node:22

# On installe pnpm, qui n'existe pas par défaut sur l'image
RUN corepack enable && corepack prepare pnpm@10.29.3 --activate

# On définit le répertoire de travail
WORKDIR /usr/src/app

# On copie les packages
COPY ./package.json ./pnpm-lock.yaml ./

# On installe les dépendances
RUN pnpm install

# On copie le gros du code
COPY . .

# On expose le corps
EXPOSE 3000

# On lance le serveur
CMD [ "pnpm", "start" ]
